version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd_user
      MYSQL_DATABASE: eval_db
      MYSQL_USER: eval_user
      MYSQL_PASSWORD: passwd_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend_src
    container_name: spring_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eval_db
      SPRING_DATASOURCE_USERNAME: eval_user
      SPRING_DATASOURCE_PASSWORD: passwd_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./frontend_src
    container_name: react_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
